#name = input(" Hey its Yash, What is your name buddy? ")
#print(f"Lets go {name},for a long drive")
#Given below is the first mini project , that is an dashboard in Electric vehicle
name1 = input("Enter your Name :-")
Car_Model = input("Get the Name of the vehicle :-")
battery_level = input("Enter the battery percantage:-")
print("----------------------------------")
print(" EV BATTERY STATUS")
print("----------------------------------")
print(" Driver name :", name1 )
print(" Car Model :", Car_Model)
print(" Battery Level :", battery_level)
print("----------------------------------")
print("THANK YOU")